'use client'
// InitializedMDXEditor.tsx
// import type { ForwardedRef } from 'react'
import {
  linkPlugin,
  linkDialogPlugin,
  headingsPlugin,
  listsPlugin,
  quotePlugin,
  thematicBreakPlugin,
  markdownShortcutPlugin,
  MDXEditor,
  // InsertImage,
  // UndoRedo, BoldItalicUnderlineToggles, toolbarPlugin,
  // type MDXEditorMethods,
  type MDXEditorProps,
  type SandpackConfig,
  codeBlockPlugin,
  sandpackPlugin,
  codeMirrorPlugin,
  // ConditionalContents,
  // ChangeCodeMirrorLanguage,
  // ShowSandpackInfo,
  // InsertSandpack,
  // InsertCodeBlock,
  imagePlugin,
  // CreateLink,
} from '@mdxeditor/editor'
import '@mdxeditor/editor/style.css'
const defaultSnippetContent = `
/**
 * Code goes here
 */
`.trim()

// Only import this to the next file
export default function InitializedMDXEditor(
  props
: MDXEditorProps) {
  return (
    <MDXEditor
      plugins={[
        linkPlugin(),
        linkDialogPlugin(),
        headingsPlugin({ allowedHeadingLevels: [1, 2, 3, 4, 5, 6] }),
        listsPlugin(),
        quotePlugin(),
        thematicBreakPlugin(),
        markdownShortcutPlugin(),
        imagePlugin(),
        codeBlockPlugin({defaultCodeBlockLanguage: 'ts'}),
        codeMirrorPlugin({ codeBlockLanguages: {
          "markup": "Markup",
          "html": "HTML",
          "xml": "XML",
          "svg": "SVG",
          "mathml": "Markup",
          "ssml": "Markup",
          "atom": "Markup",
          "rss": "Markup",
          "css": "CSS",
          "clike": "C-like",
          "javascript": "JavaScript",
          "js": "JavaScript",
          "abap": "ABAP",
          "abnf": "ABNF",
          "actionscript": "ActionScript",
          "ada": "Ada",
          "agda": "Agda",
          "al": "AL",
          "antlr4": "ANTLR4",
          "g4": "ANTLR4",
          "apacheconf": "Apache Configuration",
          "apex": "Apex",
          "apl": "APL",
          "applescript": "AppleScript",
          "aql": "AQL",
          "arduino": "Arduino",
          "ino": "Arduino",
          "arff": "ARFF",
          "armasm": "ARM Assembly",
          "arm-asm": "ARM Assembly",
          "arturo": "Arturo",
          "art": "Arturo",
          "asciidoc": "AsciiDoc",
          "adoc": "AsciiDoc",
          "aspnet": "ASP.NET (C#)",
          "asm6502": "6502 Assembly",
          "asmatmel": "Atmel AVR Assembly",
          "autohotkey": "AutoHotkey",
          "autoit": "AutoIt",
          "avisynth": "AviSynth",
          "avs": "AviSynth",
          "avro-idl": "Avro IDL",
          "avdl": "Avro IDL",
          "awk": "AWK",
          "gawk": "AWK",
          "bash": "Bash",
          "sh": "Bash",
          "shell": "Bash",
          "basic": "BASIC",
          "batch": "Batch",
          "bbcode": "BBcode",
          "shortcode": "BBcode",
          "bbj": "BBj",
          "bicep": "Bicep",
          "birb": "Birb",
          "bison": "Bison",
          "bnf": "BNF",
          "rbnf": "BNF",
          "bqn": "BQN",
          "brainfuck": "Brainfuck",
          "brightscript": "BrightScript",
          "bro": "Bro",
          "bsl": "BSL (1C:Enterprise)",
          "oscript": "BSL (1C:Enterprise)",
          "c": "C",
          "csharp": "C#",
          "cs": "C#",
          "dotnet": "C#",
          "cpp": "C++",
          "cfscript": "CFScript",
          "cfc": "CFScript",
          "chaiscript": "ChaiScript",
          "cil": "CIL",
          "cilkc": "Cilk/C",
          "cilk-c": "Cilk/C",
          "cilkcpp": "Cilk/C++",
          "cilk-cpp": "Cilk/C++",
          "cilk": "Cilk/C++",
          "clojure": "Clojure",
          "cmake": "CMake",
          "cobol": "COBOL",
          "coffeescript": "CoffeeScript",
          "coffee": "CoffeeScript",
          "concurnas": "Concurnas",
          "conc": "Concurnas",
          "csp": "Content-Security-Policy",
          "cooklang": "Cooklang",
          "coq": "Coq",
          "crystal": "Crystal",
          "css-extras": "CSS Extras",
          "csv": "CSV",
          "cue": "CUE",
          "cypher": "Cypher",
          "d": "D",
          "dart": "Dart",
          "dataweave": "DataWeave",
          "dax": "DAX",
          "dhall": "Dhall",
          "diff": "Diff",
          "django": "Django/Jinja2",
          "jinja2": "Django/Jinja2",
          "dns-zone-file": "DNS zone file",
          "dns-zone": "DNS zone file",
          "docker": "Docker",
          "dockerfile": "Docker",
          "dot": "DOT (Graphviz)",
          "gv": "DOT (Graphviz)",
          "ebnf": "EBNF",
          "editorconfig": "EditorConfig",
          "eiffel": "Eiffel",
          "ejs": "EJS",
          "eta": "EJS",
          "elixir": "Elixir",
          "elm": "Elm",
          "etlua": "Embedded Lua templating",
          "erb": "ERB",
          "erlang": "Erlang",
          "excel-formula": "Excel Formula",
          "xlsx": "Excel Formula",
          "xls": "Excel Formula",
          "fsharp": "F#",
          "factor": "Factor",
          "false": "False",
          "firestore-security-rules": "Firestore security rules",
          "flow": "Flow",
          "fortran": "Fortran",
          "ftl": "FreeMarker Template Language",
          "gml": "GameMaker Language",
          "gamemakerlanguage": "GameMaker Language",
          "gap": "GAP (CAS)",
          "gcode": "G-code",
          "gdscript": "GDScript",
          "gedcom": "GEDCOM",
          "gettext": "gettext",
          "po": "gettext",
          "gherkin": "Gherkin",
          "git": "Git",
          "glsl": "GLSL",
          "gn": "GN",
          "gni": "GN",
          "linker-script": "GNU Linker Script",
          "ld": "GNU Linker Script",
          "go": "Go",
          "go-module": "Go module",
          "go-mod": "Go module",
          "gradle": "Gradle",
          "graphql": "GraphQL",
          "groovy": "Groovy",
          "haml": "Haml",
          "handlebars": "Handlebars",
          "hbs": "Handlebars",
          "mustache": "Handlebars",
          "haskell": "Haskell",
          "hs": "Haskell",
          "haxe": "Haxe",
          "hcl": "HCL",
          "hlsl": "HLSL",
          "hoon": "Hoon",
          "http": "HTTP",
          "hpkp": "HTTP Public-Key-Pins",
          "hsts": "HTTP Strict-Transport-Security",
          "ichigojam": "IchigoJam",
          "icon": "Icon",
          "icu-message-format": "ICU Message Format",
          "idris": "Idris",
          "idr": "Idris",
          "ignore": ".ignore",
          "gitignore": ".ignore",
          "hgignore": ".ignore",
          "npmignore": ".ignore",
          "inform7": "Inform 7",
          "ini": "Ini",
          "io": "Io",
          "j": "J",
          "java": "Java",
          "javadoc": "JavaDoc",
          "javadoclike": "JavaDoc-like",
          "javastacktrace": "Java stack trace",
          "jexl": "Jexl",
          "jolie": "Jolie",
          "jq": "JQ",
          "jsdoc": "JSDoc",
          "js-extras": "JS Extras",
          "json": "JSON",
          "webmanifest": "JSON",
          "json5": "JSON5",
          "jsonp": "JSONP",
          "jsstacktrace": "JS stack trace",
          "js-templates": "JS Templates",
          "julia": "Julia",
          "keepalived": "Keepalived Configure",
          "keyman": "Keyman",
          "kotlin": "Kotlin",
          "kt": "Kotlin",
          "kts": "Kotlin",
          "kumir": "KuMir (КуМир)",
          "kum": "KuMir (КуМир)",
          "kusto": "Kusto",
          "latex": "LaTeX",
          "tex": "LaTeX",
          "context": "LaTeX",
          "latte": "Latte",
          "less": "Less",
          "lilypond": "LilyPond",
          "ly": "LilyPond",
          "liquid": "Liquid",
          "lisp": "Lisp",
          "emacs": "Lisp",
          "elisp": "Lisp",
          "emacs-lisp": "Lisp",
          "livescript": "LiveScript",
          "llvm": "LLVM IR",
          "log": "Log file",
          "lolcode": "LOLCODE",
          "lua": "Lua",
          "magma": "Magma (CAS)",
          "makefile": "Makefile",
          "markdown": "Markdown",
          "md": "Markdown",
          "markup-templating": "Markup templating",
          "mata": "Mata",
          "matlab": "MATLAB",
          "maxscript": "MAXScript",
          "mel": "MEL",
          "mermaid": "Mermaid",
          "metafont": "METAFONT",
          "mizar": "Mizar",
          "mongodb": "MongoDB",
          "monkey": "Monkey",
          "moonscript": "MoonScript",
          "moon": "MoonScript",
          "n1ql": "N1QL",
          "n4js": "N4JS",
          "n4jsd": "N4JS",
          "nand2tetris-hdl": "Nand To Tetris HDL",
          "naniscript": "Naninovel Script",
          "nani": "Naninovel Script",
          "nasm": "NASM",
          "neon": "NEON",
          "nevod": "Nevod",
          "nginx": "nginx",
          "nim": "Nim",
          "nix": "Nix",
          "nsis": "NSIS",
          "objectivec": "Objective-C",
          "objc": "Objective-C",
          "ocaml": "OCaml",
          "odin": "Odin",
          "opencl": "OpenCL",
          "openqasm": "OpenQasm",
          "qasm": "OpenQasm",
          "oz": "Oz",
          "parigp": "PARI/GP",
          "parser": "Parser",
          "pascal": "Pascal",
          "objectpascal": "Pascal",
          "pascaligo": "Pascaligo",
          "psl": "PATROL Scripting Language",
          "pcaxis": "PC-Axis",
          "px": "PC-Axis",
          "peoplecode": "PeopleCode",
          "pcode": "PeopleCode",
          "perl": "Perl",
          "php": "PHP",
          "phpdoc": "PHPDoc",
          "php-extras": "PHP Extras",
          "plant-uml": "PlantUML",
          "plantuml": "PlantUML",
          "plsql": "PL/SQL",
          "powerquery": "PowerQuery",
          "pq": "PowerQuery",
          "mscript": "PowerQuery",
          "powershell": "PowerShell",
          "processing": "Processing",
          "prolog": "Prolog",
          "promql": "PromQL",
          "properties": ".properties",
          "protobuf": "Protocol Buffers",
          "pug": "Pug",
          "puppet": "Puppet",
          "pure": "Pure",
          "purebasic": "PureBasic",
          "pbfasm": "PureBasic",
          "purescript": "PureScript",
          "purs": "PureScript",
          "python": "Python",
          "py": "Python",
          "qsharp": "Q#",
          "qs": "Q#",
          "q": "Q (kdb+ database)",
          "qml": "QML",
          "qore": "Qore",
          "r": "R",
          "racket": "Racket",
          "rkt": "Racket",
          "cshtml": "Razor C#",
          "razor": "Razor C#",
          "jsx": "React JSX",
          "tsx": "React TSX",
          "reason": "Reason",
          "regex": "Regex",
          "rego": "Rego",
          "renpy": "Ren'py",
          "rpy": "Ren'py",
          "rescript": "ReScript",
          "res": "ReScript",
          "rest": "reST (reStructuredText)",
          "rip": "Rip",
          "roboconf": "Roboconf",
          "robotframework": "Robot Framework",
          "robot": "Robot Framework",
          "ruby": "Ruby",
          "rb": "Ruby",
          "rust": "Rust",
          "sas": "SAS",
          "sass": "Sass (Sass)",
          "scss": "Sass (SCSS)",
          "scala": "Scala",
          "scheme": "Scheme",
          "shell-session": "Shell session",
          "sh-session": "Shell session",
          "shellsession": "Shell session",
          "smali": "Smali",
          "smalltalk": "Smalltalk",
          "smarty": "Smarty",
          "sml": "SML",
          "smlnj": "SML",
          "solidity": "Solidity (Ethereum)",
          "sol": "Solidity (Ethereum)",
          "solution-file": "Solution file",
          "sln": "Solution file",
          "soy": "Soy (Closure Template)",
          "sparql": "SPARQL",
          "rq": "SPARQL",
          "splunk-spl": "Splunk SPL",
          "sqf": "SQF: Status Quo Function (Arma 3)",
          "sql": "SQL",
          "squirrel": "Squirrel",
          "stan": "Stan",
          "stata": "Stata Ado",
          "iecst": "Structured Text (IEC 61131-3)",
          "stylus": "Stylus",
          "supercollider": "SuperCollider",
          "sclang": "SuperCollider",
          "swift": "Swift",
          "systemd": "Systemd configuration file",
          "t4-templating": "T4 templating",
          "t4-cs": "T4 Text Templates (C#)",
          "t4": "T4 Text Templates (C#)",
          "t4-vb": "T4 Text Templates (VB)",
          "tap": "TAP",
          "tcl": "Tcl",
          "tt2": "Template Toolkit 2",
          "textile": "Textile",
          "toml": "TOML",
          "tremor": "Tremor",
          "trickle": "Tremor",
          "troy": "Tremor",
          "turtle": "Turtle",
          "trig": "Turtle",
          "twig": "Twig",
          "typescript": "TypeScript",
          "ts": "TypeScript",
          "typoscript": "TypoScript",
          "tsconfig": "TypoScript",
          "unrealscript": "UnrealScript",
          "uscript": "UnrealScript",
          "uc": "UnrealScript",
          "uorazor": "UO Razor Script",
          "uri": "URI",
          "url": "URI",
          "v": "V",
          "vala": "Vala",
          "vbnet": "VB.Net",
          "velocity": "Velocity",
          "verilog": "Verilog",
          "vhdl": "VHDL",
          "vim": "vim",
          "visual-basic": "Visual Basic",
          "vb": "Visual Basic",
          "vba": "Visual Basic",
          "warpscript": "WarpScript",
          "wasm": "WebAssembly",
          "web-idl": "Web IDL",
          "webidl": "Web IDL",
          "wgsl": "WGSL",
          "wiki": "Wiki markup",
          "wolfram": "Wolfram language",
          "mathematica": "Wolfram language",
          "nb": "Wolfram language",
          "wl": "Wolfram language",
          "wren": "Wren",
          "xeora": "Xeora",
          "xeoracube": "Xeora",
          "xml-doc": "XML doc (.net)",
          "xojo": "Xojo (REALbasic)",
          "xquery": "XQuery",
          "yaml": "YAML",
          "yml": "YAML",
          "yang": "YANG",
          "zig": "Zig"
        }
         }),
        // toolbarPlugin({
        //   toolbarClassName: 'mdx-editor-toolbar',
        //   toolbarContents: () => (
        //     <>
        //       {' '}
        //       <UndoRedo />
        //       <BoldItalicUnderlineToggles />
        //       <CreateLink />
        //       <InsertImage />
        //       <ConditionalContents
        //         options={[
        //           { when: (editor) => editor?.editorType === 'codeblock', contents: () => <ChangeCodeMirrorLanguage /> },
        //           { when: (editor) => editor?.editorType === 'sandpack', contents: () => <ShowSandpackInfo /> },
        //           { fallback: () => ( <> 
        //           <InsertCodeBlock />
        //           <InsertSandpack />
        //         </>) }
        //         ]}
        //       />
        //     </>
        //   )
        // })
      ]}
      {...props}
    />
  )
}